name: ray-tutorial
channels:
    - conda-forge
dependencies:
  - python=3.6
  - bokeh
  - ipywidgets=6.0.0
  - tensorflow==1.14.0
  - psutil
  - nbserverproxy
  - flask
  - flask-cors
  - requests
  - pip:
    - ray[rllib]==0.7.4
    - keras
    - modin
    - matplotlib
    - bs4
    - lxml
    - scikit-learn
    - setproctitle
    - atoma
